on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install package
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
      - name: Run SQL scripts
        run: |
          psql postgres://postgres:postgres@postgres:5432/postgres -f pg/init/init.sql
      - name: Test
        run: pnpm test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
      - name: Show coverage in comments
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
